# Generated by Django 4.0.6 on 2022-07-20 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserLog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreg',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
