# Generated by Django 4.0.6 on 2022-07-20 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserLog', '0002_alter_userreg_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreg',
            name='phone_number',
            field=models.CharField(max_length=110),
        ),
    ]
